# Dynamics model parameters for G500

g500/num_actuators: 5
g500/dynamics/period: 0.001
g500/dynamics/uwsim_period: 0.001
g500/dynamics/mass: 98.0
g500/dynamics/gravity_center: [0.0, 0.0, 0.05]
g500/dynamics/g: 9.81
g500/dynamics/radius: 0.286

g500/dynamics/ctf: 0.00006835
g500/dynamics/ctb: 0.00006835

#Actuator tau for first order actuator dynamic model
g500/dynamics/actuators_tau: [0.2, 0.2, 0.2, 0.2, 0.2] 
#Inputs higher than actuators_maxsat will saturate to actuators_maxsat
g500/dynamics/actuators_maxsat: [1, 1, 1, 1, 1]        
#Inputs below actuators_minsat will saturate to actuators_minsat
g500/dynamics/actuators_minsat: [-1, -1, -1, -1, -1] 
#Inputs to actuators will be scaled to actuators_gain,
g500/dynamics/actuators_gain: [1500, 1500, 1500, 1500, 1500] 

g500/dynamics/dzv: 0.05
g500/dynamics/dv: 0.35
g500/dynamics/dh: 0.4
g500/dynamics/density: 1000.0

g500/dynamics/tensor: [8.0, 0.0, 0.0, 0.0, 8.0, 0.0, 0.0, 0.0, 8.0]
g500/dynamics/damping: [.0, .0, .0, -130.0, -130.0, -130.0]
g500/dynamics/quadratic_damping: [-148.0, -148.0, -148.0, -180.0, -180.0, -180.0]

g500/dynamics/Mrb: [ 98.0,    0.0,    0.0,    0.0,    4.9,  -0.0, 
                     0.0,   98.0,    0.0,   -4.9,   0.0,    0.0, 
                     0.0,    0.0,   98.0,    0.0,   -0.0,    0.0, 
                     0.0,   -4.9,   0.0,    8.0,    0.0,    0.0, 
                     4.9,   0.0,   -0.0,    0.0,    8.0,    0.0, 
                     -0.0,    0.0,    0.0,    0.0,    0.0,    8.0 ]

g500/dynamics/Ma: [  49.0,    0.0,    0.0,    0.0,    0.0,   0.0, 
                     0.0,    49.0,    0.0,    0.0,    0.0,   0.0, 
                     0.0,    0.0,    49.0,    0.0,    0.0,   0.0, 
                     0.0,    0.0,    0.0,    0.0,    0.0,   0.0, 
                     0.0,    0.0,    0.0,    0.0,    0.0,   0.0, 
                     0.0,    0.0,    0.0,    0.0,    0.0,   0.0 ]

#G500 thrusters. 
#Expresion evaluated at each iteration by the python interpreter
#ct is a vector internally defined such that if u[i]>0 then ct[i]=ctf, else ct[i]=ctb, i>=0 and i<number_of_actuators
#du is the vector with the control inputs
#The rest of parameters defined in this file can be referenced here as "self.param", i.e /dynamics/dh maps to "self.dh"
g500/dynamics/allocation_matrix: "
[-ct[0]*abs(du[0]),            -ct[1]*abs(du[1]),              .0,                       .0,                           .0, 
.0,                             .0,                             .0,                       .0,                           ct[4]*abs(du[4]),
.0,                             .0,                             -ct[2]*abs(du[2]),          -ct[3]*abs(du[3]),            .0, 
.0,                             .0,                             .0,                       .0,                           .0, 
.0,                             .0,                             -ct[2]*self.dv*abs(du[2]), ct[3]*self.dv*abs(du[3]),     .0, 
-ct[0]*self.dh*abs(du[0]),      ct[1]*self.dh*abs(du[1]),       .0,                       .0,                           .0]"

#Meters and Rads [X, Y, Z, Roll, Pitch, Yaw]
g500/dynamics/initial_pose: [0.0, 0.0, 0.0, 0, 0, 1.57] #[3.0, 1.1, 2.8, 0, 0, 3.14]
g500/dynamics/initial_velocity: [0, 0, 0, 0, 0, 0]

g500/dynamics/topic_name: "/dataNavigator"
g500/dynamics/external_force_topic: "/g500/external_force"
g500/dynamics/frame_id: "g500_base_link"


#WATER CURRENTs SIMULATION
dynamics/current_mean: [0.05, 0, 0]
dynamics/current_sigma: [0.002, 0.001, 0.001]
dynamics/current_min: [0.0, 0.0, 0.0]
dynamics/current_max: [0.0, 0.0, 0.0]

