controllers:
    config:
        joints:
            state: joint_states
            setpoint: joint_setpoint
            command: joint_command
            cascaded_position: False
            dynamic_reconfigure: True
    Slew:
        velocity: {p: 1.0, i: 0., d: 0.0}
        position: {p: 10, i: 0.1, d: 0.5}
    Shoulder:
        velocity: {p: 1.0, i: 0.1, d: 0.0}
        position: {p: 10, i: 0.1, d: 0.5}
    Elbow:
        velocity: {p: 1.0, i: 0.1, d: 0.0}
        position: {p: 10, i: 0.1, d: 0.5}
    JawRotate:
        velocity: {p: 1.0, i: 0.1, d: 0.0}
        position: {p: 10, i: 0.01, d: 0.5}
    JawOpening:
        velocity: {p: 1.0, i: 0.1, d: 0.0}
        position: {p: 1, i: 0.01, d: 0.5}
    JawOpening2:
        velocity: {p: 1.0, i: 0.1, d: 0.0}
        position: {p: 1, i: 0.01, d: 0.5}
