TrajectoryPlannerROS:
    max_vel_x: 0.5
    min_vel_x: 0.0
    max_vel_theta: 0.3
    min_in_place_vel_theta: 0.1

    acc_lim_theta: 3.2
    acc_lim_x: 2.5
    acc_lim_y: 2.5

    holonomic_robot: false
